## Numpy array and basics


In [2]:
import numpy as np


### creating array from list

In [3]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

arr_2d =  np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


### List vs numpy array


In [4]:
py_list = [1,2,3,4,5]
print("python list multiplication",py_list*2) 

np_array = np.array([2,34,5,6]) # element wise multiplication
print("python array multiplication: ", np_array *2)


python list multiplication [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
python array multiplication:  [ 4 68 10 12]


In [5]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:",time.time() - start) 

start = time.time()
np_array = np.arange(1000000)*2 # arange is kitne range ka karana hai
print("\n Numpy operation time:",time.time() - start)
# numpy is efficient



 List operation time: 0.04093742370605469

 Numpy operation time: 0.0035696029663085938


### Creating array from scratch

In [6]:
zeros = np.zeros((3,4)) 
print("zeros array:\n",zeros)

ones = np.ones((2,3))
print("ones array:\n",ones)

full = np.full((2,2),7)
print("full array:\n",full) 

random = np.random.random((2,3))
print("random array:\n",random) 

sequence = np.arange(0,10,2)
print("sequence array:\n",sequence) 


zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array:
 [[0.25327565 0.39026074 0.90565608]
 [0.32805182 0.25091402 0.45830156]]
sequence array:
 [0 2 4 6 8]


### Vector, Matrices and Tensor

In [7]:
vector = np.array([1,2,3])
print("vector:\n",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix:\n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]]) 
print("Tensor:\n",tensor)


vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties
Numpy array is optimized as it has only similar data types

In [8]:
arr = np.array([[1,2,3],
                [4,5,6]]) 

print("Shape:\n",arr.shape) 
print("Dimension:\n",arr.ndim) 
print("Size:\n",arr.size) 
print("Dtype:\n",arr.dtype)  # this can be reduced as well. 



Shape:
 (2, 3)
Dimension:
 2
Size:
 6
Dtype:
 int64


### Array Reshaping

In [9]:
arr = np.arange(12)
print("original array:",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array:\n",reshaped)

flattened = reshaped.flatten() # return copy
print("Flattened array:\n",flattened)

# ravel (return view, instead of copy) - this return original array
raveled = reshaped.ravel()
print("Raveled array:\n",raveled)

# Transpose 
transpose = reshaped.T
print("Transposed array:\n",transpose)


original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
