## Numpy Array operations

In [88]:
import numpy as np

### Indexing 

In [89]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing:",arr[2:7])
print("With Step:",arr[::2])
print("Negative Indexing",arr[-3])

Basic slicing: [3 4 5 6 7]
With Step: [1 3 5 7 9]
Negative Indexing 7


In [90]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[2,1]) 
print("Whole row",arr_2d[2])
print("entire column",arr_2d[:,1]) 
# colon is used to denote no row and then after comma you write the column you 
# want to print.

Specific element 8
Whole row [7 8 9]
entire column [2 5 8]


### Sorting

In [91]:
unsorted = np.array([3,1,4,5,9,2,6])
print("sorted 1D array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2D array by column:",np.sort(arr_2d_unsorted,axis = 0))
print("Sorted 2D array by row:",np.sort(arr_2d_unsorted,axis = 1))


sorted 1D array: [1 2 3 4 5 6 9]
Sorted 2D array by column: [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row: [[1 3]
 [1 2]
 [2 3]]


### Filter

In [92]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] 
# here we are writing expressions to get them evaluated to recieve the output
print("even numbers", even_number)



even numbers [ 2  4  6  8 10]


## Filter with mask
[numbers % 2 == 0] this term is the mask.
MASK - is a term/ expression which performs evaluation.  

In [93]:
mask = numbers > 5
print("numbers greater than 5 :", numbers[mask]) 

numbers greater than 5 : [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [94]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result) # holds the number index
print("NP where:",numbers[where_result]) # prints the values of that index



[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]


In [95]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array) 
# executing on numbers array. 

condition_array = np.where(numbers > 5, "True","false" )
print(condition_array) 


[ 1  2  3  4  5 24 28 32 36 40]
['false' 'false' 'false' 'false' 'false' 'True' 'True' 'True' 'True'
 'True']


In [96]:
"""
if(numbers > 5) {
    numbers*4
} else { 
numbers
}
the above code a the long format of the below code:
np.where(numbers > 5, numbers*4, numbers) 
which means that if numbers > 5 then print numbers *4 else print numbers.

"""

'\nif(numbers > 5) {\n    numbers*4\n} else { \nnumbers\n}\nthe above code a the long format of the below code:\nnp.where(numbers > 5, numbers*4, numbers) \nwhich means that if numbers > 5 then print numbers *4 else print numbers.\n\n'

### Adding or removing data

In [97]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
print("COMBINED WITH PLUS:",combined)

concatenate = np.concatenate((arr1,arr2))
print("concatenate:",concatenate)


COMBINED WITH PLUS: [5 7 9]
concatenate: [1 2 3 4 5 6]


### Array compatibility

In [98]:
a = np.array([1,2,3])
b = np.array([5,6,4,4])
c = np.array([7,8,9]) 


print("compatibility shapes:", a.shape == b.shape)

compatibility shapes: False


In [99]:
original = np.array([[1,2],
                     [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row)) # vstack = vertical stack
print("Original:\n",original)
print("With new row\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("With new column:\n",with_new_col) 


Original:
 [[1 2]
 [3 4]]
With new row
 [[1 2]
 [3 4]
 [5 6]]
With new column:
 [[1 2 7]
 [3 4 8]]


In [100]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)
print("array after deletion:\n",deleted)

array after deletion:
 [1 2 4 5 6]


In [101]:
sliced = np.arange(1,31).reshape(6,5)
sliced

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [102]:
sliced[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [103]:
sliced[:,1]

array([ 2,  7, 12, 17, 22, 27])

### BOOLEAN INDEXING 

In [104]:
array = np.arange(11,21) 
array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [105]:
bool_index = array % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [106]:
array = array[bool_index]
array

array([12, 14, 16, 18, 20])

### BROADCASTING

In [107]:
l = [10,20,30,40] 
nrr= np.array(l)
nrr+10

array([20, 30, 40, 50])

> DEEP & SHALLOW COPY 

SHALLOW COPY

In [108]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [109]:
abhis=a[:5]
abhis = abhis**2
abhis

array([ 1,  4,  9, 16, 25])

In [110]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [111]:
a[4:6]*10

array([50, 60])

DEEP COPY

In [115]:
a
b=a

In [116]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [117]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### MATRIX MULTIPLICATION 

In [118]:
A = np.array([[1,2],[3,4]]) 

In [121]:
B = np.array([[5,6],[7,8]])

In [ ]:
A@B

array([[19, 22],
       [43, 50]])

In [127]:
C = np.dot(A,B)
C

array([[19, 22],
       [43, 50]])

In [130]:
C.T # returns shallow copy

array([[19, 43],
       [22, 50]])

In [131]:
C

array([[19, 22],
       [43, 50]])

### ADVANCED ARRAY MANIPULATION

In [132]:
A 

array([[1, 2],
       [3, 4]])

In [133]:
B

array([[5, 6],
       [7, 8]])

> ARRAY STACKING

In [134]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [135]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [139]:
c = np.array([1,2])
d = np.array([6,7])

In [140]:
np.column_stack((c,d))

array([[1, 6],
       [2, 7]])

### SPLITTING ARRAY

In [147]:
A

array([[1, 2],
       [3, 4]])

In [149]:
np.hsplit(A,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [150]:
np.vsplit(A,2)

[array([[1, 2]]), array([[3, 4]])]