## Numpy array and basics


In [21]:
import numpy as np

### creating array from list

In [22]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

arr_2d =  np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


### List vs numpy array


In [23]:
py_list = [1,2,3,4,5]
print("python list multiplication",py_list*2) 

np_array = np.array([2,34,5,6]) # element wise multiplication
print("python array multiplication: ", np_array *2)


python list multiplication [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
python array multiplication:  [ 4 68 10 12]


In [24]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:",time.time() - start) 

start = time.time()
np_array = np.arange(1000000)*2 # arange is kitne range ka karana hai
print("\n Numpy operation time:",time.time() - start)
# numpy is efficient



 List operation time: 0.08943629264831543

 Numpy operation time: 0.005899906158447266


### Creating array from scratch

In [25]:
zeros = np.zeros((3,4)) 
print("zeros array:\n",zeros)

ones = np.ones((2,3))
print("ones array:\n",ones)

full = np.full((2,2),7)
print("full array:\n",full) 

random = np.random.rand(10)
print("random array (Normalization-0,1):\n",random) 

random2 = np.random.random((3,2))
print("Second random array:\n",random2)

random3 = np.random.randn(10)
print("Standardization(-3,3) Random array\n",random3)

randomint = np.random.randint(6)
print("random number between 0 & the given number:",randomint)

sequence = np.arange(0,10,2)
print("sequence array:\n",sequence) 

linear_space = np.linspace(0,1,5)
print("linear space array:\n",linear_space)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array (Normalization-0,1):
 [0.20181191 0.48288442 0.99749516 0.33380636 0.62102299 0.06764163
 0.20180982 0.49794659 0.51507488 0.05331829]
Second random array:
 [[0.37009359 0.60936333]
 [0.87157502 0.16974024]
 [0.06983799 0.88206193]]
Standardization(-3,3) Random array
 [ 1.62458606 -0.41420662  2.64298495  0.41900382  0.01979551 -1.59836518
 -0.59879468  0.96201758  0.74447559 -1.1064994 ]
random number between 0 & the given number: 3
sequence array:
 [0 2 4 6 8]
linear space array:
 [0.   0.25 0.5  0.75 1.  ]


### Vector, Matrices and Tensor

In [26]:
vector = np.array([1,2,3])
print("vector:\n",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix:\n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]]) 
print("Tensor:\n",tensor)


vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties
Numpy array is optimized as it has only similar data types

In [27]:
arr = np.array([[1,2,3],
                [4,5,6]]) 

print("Shape:\n",arr.shape) 
print("Dimension:\n",arr.ndim) 
print("Size:\n",arr.size) 
print("Dtype:\n",arr.dtype)  # this can be reduced as well. 



Shape:
 (2, 3)
Dimension:
 2
Size:
 6
Dtype:
 int64


### Array Reshaping

In [28]:
arr = np.arange(12)
print("original array:",arr)

reshaped = arr.reshape((3,4))
print("Reshaped array:\n",reshaped)

flattened = reshaped.flatten() # return copy
print("Flattened array:\n",flattened)

# ravel (return view, instead of copy) - this return original array
raveled = reshaped.ravel()
print("Raveled array:\n",raveled)

# Transpose 
transpose = reshaped.T
print("Transposed array:\n",transpose)


original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [29]:
np.sum(reshaped,axis=0)

array([12, 15, 18, 21])

In [30]:
np.sum(reshaped,axis=1)

array([ 6, 22, 38])

> argmax() & argmin() is used to find the index of the largest element index and the lowest index element.