## Numpy Array operations

In [38]:
import numpy as np

### Indexing 

In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing:",arr[2:7])
print("With Step:",arr[::2])
print("Negative Indexing",arr[-3])

Basic slicing: [3 4 5 6 7]
With Step: [1 3 5 7 9]
Negative Indexing 7


In [40]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[2,1]) 
print("Whole row",arr_2d[2])
print("entire column",arr_2d[:,1]) 
# colon is used to denote no row and then after comma you write the column you 
# want to print.

Specific element 8
Whole row [7 8 9]
entire column [2 5 8]


### Sorting

In [41]:
unsorted = np.array([3,1,4,5,9,2,6])
print("sorted 1D array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2D array by column:",np.sort(arr_2d_unsorted,axis = 0))
print("Sorted 2D array by row:",np.sort(arr_2d_unsorted,axis = 1))


sorted 1D array: [1 2 3 4 5 6 9]
Sorted 2D array by column: [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row: [[1 3]
 [1 2]
 [2 3]]


### Filter

In [42]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] 
# here we are writing expressions to get them evaluated to recieve the output
print("even numbers", even_number)



even numbers [ 2  4  6  8 10]


## Filter with mask
[numbers % 2 == 0] this term is the mask.
MASK - is a term/ expression which performs evaluation.  

In [43]:
mask = numbers > 5
print("numbers greater than 5 :", numbers[mask]) 

numbers greater than 5 : [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [44]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result) # holds the number index
print("NP where:",numbers[where_result]) # prints the values of that index



[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where: [ 6  7  8  9 10]


In [45]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array) 
# executing on numbers array. 

condition_array = np.where(numbers > 5, "True","false" )
print(condition_array) 


[ 1  2  3  4  5 24 28 32 36 40]
['false' 'false' 'false' 'false' 'false' 'True' 'True' 'True' 'True'
 'True']


In [46]:
"""
if(numbers > 5) {
    numbers*4
} else { 
numbers
}
the above code a the long format of the below code:
np.where(numbers > 5, numbers*4, numbers) 
which means that if numbers > 5 then print numbers *4 else print numbers.

"""

'\nif(numbers > 5) {\n    numbers*4\n} else { \nnumbers\n}\nthe above code a the long format of the below code:\nnp.where(numbers > 5, numbers*4, numbers) \nwhich means that if numbers > 5 then print numbers *4 else print numbers.\n\n'

### Adding or removing data

In [47]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
print("COMBINED WITH PLUS:",combined)

concatenate = np.concatenate((arr1,arr2))
print("concatenate:",concatenate)


COMBINED WITH PLUS: [5 7 9]
concatenate: [1 2 3 4 5 6]


### Array compatibility

In [48]:
a = np.array([1,2,3])
b = np.array([5,6,4,4])
c = np.array([7,8,9]) 


print("compatibility shapes:", a.shape == b.shape)

compatibility shapes: False


In [49]:
original = np.array([[1,2],
                     [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row)) # vstack = vertical stack
print("Original:\n",original)
print("With new row\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("With new column:\n",with_new_col) 


Original:
 [[1 2]
 [3 4]]
With new row
 [[1 2]
 [3 4]
 [5 6]]
With new column:
 [[1 2 7]
 [3 4 8]]


In [50]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)
print("array after deletion:\n",deleted)

array after deletion:
 [1 2 4 5 6]


In [51]:
sliced = np.arange(1,31).reshape(6,5)
sliced

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [52]:
sliced[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [53]:
sliced[:,1]

array([ 2,  7, 12, 17, 22, 27])

### BOOLEAN INDEXING 

In [54]:
array = np.arange(11,21) 
array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
bool_index = array % 2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [58]:
array = array[bool_index]
array

array([12, 14, 16, 18, 20])