## VALID SUDOKU PROBLEM CHECK. 

In [243]:
import numpy as np

In [244]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

> Get the sum of each and every row & column. 

In [245]:
row_sum = np.sum(s,axis=1)
row_sum==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [246]:
col_sum = np.sum(s,axis=0)
col_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

> Check the sum of each 3X3 block is 45 or not.

In [247]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [248]:
for i in range(0,9,3):  # iterates over row indices in steps of 3 -> 0,3,6.
    for j in range(0,9,3): # iterates over column indices in steps of 3 -> 0,3,6.
        n = s[i:i+3,j:j+3]
        block_sum = np.sum(n)
        print(block_sum)

45
45
45
45
45
45
45
45
45


In [249]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

> Get the shape of matrix

In [250]:
data.shape

(5, 3)

> find the average age of students. 

In [251]:
np.average(data[:,0])

np.float64(18.4)

> Extract the math marks of all students. 

In [252]:
data[:,1]

array([85, 92, 76, 65, 90])

> Find the highest Science mark. 

In [253]:
np.max(data[:,2])

np.int64(95)

> Get details of the student who scored more than 90 in Math.

In [254]:
data[data[:,1] > 90]
# data[mask]
# This is boolean indexing. It returns only the rows where the mask is True

array([[19, 92, 88]])

> Increase math marks of all students by 5.

In [255]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [256]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

> Find how many students are younger than 19. 

In [257]:
np.sum(data[:,0]<19)

np.int64(3)

> Calculate the average marks in each subject (column-wise mean).

In [258]:
np.average(data[:,1:],axis=0)

array([86.6, 83.2])

> Get data of students who scored at least 80 in both sujects.

In [259]:
data[(data[:,1] >=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

> Replace all Science marks <75 with 0.

In [260]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [261]:
data[data[:,2] <75,2] =0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])